# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
notifications:
email: false

addons:
  apt:
    packages:
      # pgfplots
      - pdf2svg
      - texlive-latex-base
      - texlive-binaries
      - texlive-pictures
      - texlive-latex-extra
      # plotlyjs
      - xvfb
      # orca
      - libgconf2-4
env:
  matrix:
    - PYTHON=""

# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - xvfb-run julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
